---
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0"
matrix:
  fast_finish: true
notifications:
  email: false
